# Generated by Django 4.0.4 on 2022-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_diary_diary_img_alter_diary_diary_share_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
