# Generated by Django 3.2.13 on 2022-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_diary_diary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_auth_type',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_delivery_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
