# Generated by Django 4.0.4 on 2022-05-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_diary_diary_share_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_img',
            field=models.ImageField(blank=True, default='default_img/diary_default_img.png', null=True, upload_to='diary_img/'),
        ),
    ]
