# Generated by Django 4.0.4 on 2022-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_signup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
