# Generated by Django 3.2.13 on 2022-06-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220607_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userimage'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
