# Generated by Django 3.2.13 on 2022-06-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220607_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='user_id',
        ),
    ]
