# Generated by Django 3.2.13 on 2022-06-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_userimage_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
