# Generated by Django 3.2.13 on 2022-06-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_qna_qna_img'),
        ('main', '0031_userimage_user_id'),
    ]

    operations = [
    ]
