# Generated by Django 3.2.13 on 2022-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_merge_0012_alter_qna_qna_img_0031_userimage_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercount',
            name='basket',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
