# Generated by Django 4.0.4 on 2022-06-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_merge_0012_alter_qna_qna_img_0031_userimage_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='product_img/'),
        ),
    ]
