# Generated by Django 4.0.4 on 2022-06-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220609_1535'),
        ('main', '0035_alter_product_product_img'),
    ]

    operations = [
    ]
