# Generated by Django 4.0.4 on 2022-06-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_order_order_agree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_username',
            new_name='order_user_name',
        ),
    ]
